✅ ১. NumPy কী?

NumPy (Numerical Python) হচ্ছে একটি powerful লাইব্রেরি, যেটা দিয়ে numerical computation, array, matrix operation অনেক efficient ও দ্রুত করা যায়।

Python-এর list অনেক ধীরগতি, আর NumPy এর array (called ndarray) অনেক দ্রুত (50x faster) এবং memory-efficient।



 # ARRAY

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

In [ ]:
import numpy as np

✅ NumPy ndarray Object


In [ ]:
arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 0-D Arrays

arr0 = np.array(34)
print(arr0)

34


In [ ]:
# 1-D Arrays

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
# 2-D array

arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3-D array

# two 2-D arrays, elements number will be same;

arr3 = np.array([[[1,2,3],[4,5,6]],[[2,4,6],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[2 4 6]
  [4 5 6]]]


In [ ]:
# Check Number of Dimensions

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a dimension: ", a.ndim)
print("b dimension: ", b.ndim)
print("c dimension: ", c.ndim)
print("d dimension: ", d.ndim)

a dimension:  0
b dimension:  1
c dimension:  2
d dimension:  3


✅ Higher Dimensional Arrays

An array can have any number of dimensions.

In [ ]:
arr= np.array([1,2,3,4,5], ndmin=5)    # 5 dimensional array using "ndmin"

print(arr)
print("Number of Dimension: ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of Dimension:  5


# Array Indexing


In [ ]:
arr = np.array([1,2,3,4,5])

print("First Element: ",arr[0])
print("Second Element: ",arr[1])
print("Third Element: ",arr[2])

First Element:  1
Second Element:  2
Third Element:  3


In [ ]:
# Try to add

arr= np.array([2,3,4,5,6])

sum = arr[0] + arr[1]

print("Sum = ", sum)

Sum =  5


In [ ]:
# Access 2-D Arrays

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Second element of the 1st row is: ", arr[0,1])
print("fourth element of the 2nd row is: ", arr[1,3])

Second element of the 1st row is:  2
fourth element of the 2nd row is:  9


In [ ]:
# Access 3-D Arrays

# try to access 2nd element of the 3rd row
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print("2nd element of the 3rd row: ",arr[1,0,1])

2nd element of the 3rd row:  8


#Negative Indexing

negative indexing access an array from the end.



In [ ]:
arr = np.array([1,2,3,4,5])
print("Last Element: ",arr[-1])
print("Second Last Element: ",arr[-2])

Last Element:  5
Second Last Element:  4


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Last Element from 2nd row: ",arr[1,-2])  #here, -2 means second last element and 1 means 2nd row that holds index number 1.

Last Element from 2nd row:  9


# Array Slicing

...Slicing in python means taking elements from one given index to another given index.

...We pass slice instead of index like this: [start : end].

...We can also define the step, like this: [start : end : step].

...If we don't pass start its considered 0

...If we don't pass end its considered length of array in that dimension

...If we don't pass step its considered 1

In [ ]:
# 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print("1 to index 5 : ", arr[1 : 5])  # The result includes the start index, but excludes the end index.

print("1 to index 5 with step 2 : ", arr[1 : 5 : 2])

print("First to index 5 : ", arr[ : 5])

print("index 2 to last : ", arr[2 : ])

print("index 3 to last with step 2 : ", arr[3: : 2])


1 to index 5 :  [2 3 4 5]
1 to index 5 with step 2 :  [2 4]
First to index 5 :  [1 2 3 4 5]
index 2 to last :  [3 4 5 6 7 8]
index 3 to last with step 2 :  [4 6 8]


In [ ]:
# Negative Slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print("Last 3 elements : ", arr[-3 : ])

print("Last 3 elements with step 2 : ", arr[-3 : : 2])

Last 3 elements :  [6 7 8]
Last 3 elements with step 2 :  [6 8]


In [ ]:
# Slicing 2-D Arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# From the second element, slice elements from index 1 to index 4 (not included)
print (arr[1, 1:4])

[7 8 9]


In [ ]:
arr= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# From both elements, return index 2:
print(arr[0:2, 2])

# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
#Array-এর তথ্য বের করা

print("Arr1 size: ", arr1.size)   #array size
print("Arr2 size: ", arr2.size)

print("Dimension: ", arr1.ndim)   #dimension
print("Dimension: ", arr2.ndim)   #dimension

print("Arr1 shape: ", arr1.shape)  #array shape (প্রতিটি ডাইমেনশনে কত উপাদান)
print("Arr2 shape: ", arr2.shape)

print("Type", arr1.dtype)   #datatype

Arr1 size:  5
Arr2 size:  9
Dimension:  1
Dimension:  2
Arr1 shape:  (5,)
Arr2 shape:  (3, 3)
Type int64
