# NumPy Array Iterating

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])

for x in arr:
  print(x)

1
2
3
4
5
6


In [3]:
# Iterating 2-D Arrays
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
  print(x)

[1 2 3 4]
[5 6 7 8]


In [4]:
# Iterating 2-D Arrays
arr= np.array([[1,2,3],[4,5,6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [5]:
# 3-D Array

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()
  The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

  Iterating on Each Scalar Element
  In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [9]:
# Iterate through the following 3-D array:

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.


NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [11]:
arr = np.array([1,2,3,4,5])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

# here it prints byte type string

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')


In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[ :, : : 2]):
  print(x)


1
3
5
7


In [13]:
arr = np.array([1,2,3,4,5])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
