In [1]:
import numpy as np

# Data Types in NumPy
The NumPy array object has a property called "dtype" that returns the data type of the array

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

In [2]:
arr = np.array([1,2,3,4,5])

print("Data type of this array is : ", arr.dtype)

Data type of this array is :  int64


In [4]:
arr=np.array(["apple", "banana", "orange"])

print("Data type of this array is : ", arr.dtype)

Data type of this array is :  <U6


In [8]:
arr = np.array([1,2,3,4,5], dtype="S")

print(arr)

print("Data type of this array is : ", arr.dtype)

# b মানে হচ্ছে "bytes", অর্থাৎ এই অ্যারে-র প্রতিটি উপাদান হচ্ছে bytes string (byte ধারার স্ট্রিং)।
# |S1 = byte string dtype with length 1

[b'1' b'2' b'3' b'4' b'5']
Data type of this array is :  |S1


In [10]:
arr = np.array([1,2,3,4,5,6], dtype="i4")   # 4 byte integer

print(arr)
print("Data type of this array is : ", arr.dtype)

[1 2 3 4 5 6]
Data type of this array is :  int32


# Converting Data Type on Existing Arrays
    The best way to change the data type of an existing array, is to make a copy of the array with the "astype()" method.

    The "astype()" function creates a copy of the array, and allows you to specify the data type as a parameter.

    The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [21]:
arr = np. array([1,2,0,4,5])

new_arr1 = arr.astype('i')
new_arr2 = arr.astype('f')
new_arr3 = arr.astype(bool)

print(new_arr1)
print("new_arr1 data type: ", new_arr1.dtype)
print(new_arr2)
print("new_arr2 data type: ", new_arr2.dtype)
print(new_arr3)
print("new_arr3 data type: ", new_arr3.dtype)


[1 2 0 4 5]
new_arr1 data type:  int32
[1. 2. 0. 4. 5.]
new_arr2 data type:  float32
[ True  True False  True  True]
new_arr3 data type:  bool


In [20]:
arr = np.array([1.1, 2.2, 3.3, 4.4])

new_arr = arr.astype(int)

print(new_arr)
print("new_arr data type: ", new_arr.dtype)

[1 2 3 4]
new_arr data type:  int64


# NumPy Array Copy vs View
    The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

    The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

    The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])

x = arr.copy()

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [5]:
# View

arr = np.array([1,2,3,4,5])

x = arr.view()

arr[0]= 34

print(arr)
print(x)

[34  2  3  4  5]
[34  2  3  4  5]


    Every NumPy array has the attribute base that returns None if the array owns the data.

    Otherwise, the base  attribute refers to the original object.

In [6]:
arr = np.array([1,2,3,4,5])

x = arr.view()
y = arr.copy()

print(x.base)
print(y.base)

[1 2 3 4 5]
None


# Shape of an Array
The shape of an array is the number of elements in each dimension. like the size of matrix (m*n)

In [9]:
arr = np.array([[1,2,3,4,5],[1,3,5,7,9]])

print("It's Shape is: ", arr.shape)


It's Shape is:  (2, 5)


In [10]:
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print("Shape of this array is: ", arr.shape)

[[[[[1 2 3 4]]]]]
Shape of this array is:  (1, 1, 1, 1, 4)


In [1]:
import numpy as np

In [2]:
# Reshape From 1-D to 2-D

arr = np.array([1,2,3,4,5,6,7,8,9,10])

new_arr1 = arr.reshape(2,5)
new_arr2 = arr.reshape(5,2)

print("arr : ",arr)
print("new_arr1 : ",new_arr1)
print("new_arr2 : ",new_arr2)

arr :  [ 1  2  3  4  5  6  7  8  9 10]
new_arr1 :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
new_arr2 :  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [5]:
# Reshape From 1-D to 3-D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arr1 = arr.reshape(2,3,2)
# here, 2 arrays that contains 3 arrays, each with 2 elements

print("Main array : ", arr)
print("Reshaped array : ", arr1)

Main array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array :  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [15]:
# Flattening the arrays

arr = np.array([[1,2,3,4],[2,3,4,5]])

new_arr = arr.reshape(-1)   #Convert the array into a 1D array

print(new_arr)

[1 2 3 4 2 3 4 5]
