In [1]:
import numpy as np

# NumPy Joining Array

✔ Joining means putting contents of two or more arrays in a single array.

✔ In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

✔ We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6 7 8]


In [8]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[6,7],[8,9]])

arrX = np.concatenate((arr1, arr2))
arrY = np.concatenate((arr1, arr2),axis=1)

print(arrX)

print("\n without axis")
print(arrY)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]

 without axis
[[1 2 6 7]
 [3 4 8 9]]


# Joining Arrays Using Stack Functions
✔ Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

✔ We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

✔ We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [16]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2), axis=1)

print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# NumPy provides a helper function: hstack() to stack along rows.

In [17]:
# hstack
# represents column as rows
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.array([[1,2,3],[11,22,33]])
arr4 = np.array([[4,5,6],[44,55,66]])

arrX = np.hstack((arr1,arr2))  #same as 1-d concatenate
arrY = np.hstack((arr3,arr4))

print("For 1-D array: ", arrX)
print("For 1-D array: ", arrY)

For 1-D array:  [1 2 3 4 5 6]
For 1-D array:  [[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


# NumPy provides a helper function: vstack()  to stack along columns.

In [18]:
# vstack()
# Represent rows as columns

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.array([[1,2,3],[11,22,33]])
arr4 = np.array([[4,5,6],[44,55,66]])

arrX = np.vstack((arr1, arr2))
arrY = np.vstack((arr3, arr4))

print(arrX)
print(arrY)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [11 22 33]
 [ 4  5  6]
 [44 55 66]]


# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.array([[1,2,3],[11,22,33]])
arr4 = np.array([[4,5,6],[44,55,66]])

arrX = np.dstack((arr1, arr2))
arrY = np.dstack((arr3, arr4))

print("For 1-D array: ", arrX)
print("For 2-D array: \n", arrY)

For 1-D array:  [[[1 4]
  [2 5]
  [3 6]]]
For 2-D array: 
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[11 44]
  [22 55]
  [33 66]]]
