✅ ১. NumPy কী?

NumPy (Numerical Python) হচ্ছে একটি powerful লাইব্রেরি, যেটা দিয়ে numerical computation, array, matrix operation অনেক efficient ও দ্রুত করা যায়।

Python-এর list অনেক ধীরগতি, আর NumPy এর array (called ndarray) অনেক দ্রুত এবং memory-efficient।



ARRAY

In [1]:
import numpy as np

In [2]:
#1D Array

arr1= np.array([1,2,3,4,5]);
print(arr1)

[1 2 3 4 5]


In [5]:
#2D array

arr2= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Array-এর তথ্য বের করা

print("Arr1 size: ", arr1.size)   #array size
print("Arr2 size: ", arr2.size)

print("Dimension: ", arr1.ndim)   #dimension
print("Dimension: ", arr2.ndim)   #dimension

print("Arr1 shape: ", arr1.shape)  #array shape (প্রতিটি ডাইমেনশনে কত উপাদান)
print("Arr2 shape: ", arr2.shape)

print("Type", arr1.dtype)   #datatype

Arr1 size:  5
Arr2 size:  9
Dimension:  1
Dimension:  2
Arr1 shape:  (5,)
Arr2 shape:  (3, 3)
Type int64
