In [1]:
import numpy as np

# Data Types in NumPy
The NumPy array object has a property called "dtype" that returns the data type of the array

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

In [2]:
arr = np.array([1,2,3,4,5])

print("Data type of this array is : ", arr.dtype)

Data type of this array is :  int64


In [4]:
arr=np.array(["apple", "banana", "orange"])

print("Data type of this array is : ", arr.dtype)

Data type of this array is :  <U6


In [8]:
arr = np.array([1,2,3,4,5], dtype="S")

print(arr)

print("Data type of this array is : ", arr.dtype)

# b মানে হচ্ছে "bytes", অর্থাৎ এই অ্যারে-র প্রতিটি উপাদান হচ্ছে bytes string (byte ধারার স্ট্রিং)।
# |S1 = byte string dtype with length 1

[b'1' b'2' b'3' b'4' b'5']
Data type of this array is :  |S1


In [10]:
arr = np.array([1,2,3,4,5,6], dtype="i4")   # 4 byte integer

print(arr)
print("Data type of this array is : ", arr.dtype)

[1 2 3 4 5 6]
Data type of this array is :  int32


# Converting Data Type on Existing Arrays
    The best way to change the data type of an existing array, is to make a copy of the array with the "astype()" method.

    The "astype()" function creates a copy of the array, and allows you to specify the data type as a parameter.

    The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [21]:
arr = np. array([1,2,0,4,5])

new_arr1 = arr.astype('i')
new_arr2 = arr.astype('f')
new_arr3 = arr.astype(bool)

print(new_arr1)
print("new_arr1 data type: ", new_arr1.dtype)
print(new_arr2)
print("new_arr2 data type: ", new_arr2.dtype)
print(new_arr3)
print("new_arr3 data type: ", new_arr3.dtype)


[1 2 0 4 5]
new_arr1 data type:  int32
[1. 2. 0. 4. 5.]
new_arr2 data type:  float32
[ True  True False  True  True]
new_arr3 data type:  bool


In [20]:
arr = np.array([1.1, 2.2, 3.3, 4.4])

new_arr = arr.astype(int)

print(new_arr)
print("new_arr data type: ", new_arr.dtype)

[1 2 3 4]
new_arr data type:  int64
